target: price

num_features:
  - manufactured
  - no_of_owners
  - omv
  - features_num_words
  - features_num_unique_words
  - features_num_chars
  - features_num_stopwords
  - features_num_punctuations
  - features_mean_word_len
  - accessories_num_words
  - accessories_num_unique_words
  - accessories_num_chars
  - accessories_num_stopwords
  - accessories_num_punctuations
  - accessories_mean_word_len
  - description_num_words
  - description_num_unique_words
  - description_num_chars
  - description_num_stopwords
  - description_num_punctuations
  - description_mean_word_len
  - coe_date_year
  - coe_month_left
  - is_lifespan_missing
  - lifespan_year
  - reg_date_year
  - manufactured_to_reg_year
  - lifespan_to_reg_year
  - car_age
  - car_age_manufactured
  - arf_fill
  - coe_fill
  - coe_missing
  - dereg_value_fill
  - depreciation_fill
  - road_tax_fill
  - power_missing
  - power_fill
  - curb_weight_missing
  - curb_weight_fill
  - engine_cap_missing 
  - engine_cap_fill
  - mileage_missing
  - mileage_fill

cat_encoding_features:
  - is_auto
  - is_manual
  - is_missing
  - is_diesel
  - is_petrol-electric
  - is_petrol
  - is_electric
  - is_mid-sized sedan
  - is_sports car
  - is_truck
  - is_stationwagon
  - is_suv
  - is_mpv
  - is_luxury sedan
  - is_hatchback
  - is_van
  - is_bus/mini bus
  - is_others
  - is_warranty
  - is_loan
  - is_coe_car
  - is_hybrid_cars
  - is_sta_evaluated_car
  - is_opc_car
  - is_low_mileage_car
  - is_premium_ad_car
  - is_rare__exotic
  - is_direct_owner_sale
  - is_vintage_cars
  - is_almost_new_car
  - is_electric_cars
  - is_parf_car
  - is_sgcarmart_warranty_cars
  - is_imported_used_vehicle
  - is_consignment_car

cat_feature_encoding:
  - price_count_make_fill
  - price_count_make_model
  - price_count_type_of_vehicle
  - price_count_transmission
  - price_count_fuel_type
  - make_fill_jse_encode
  - make_model_jse_encode
  - type_of_vehicle_jse_encode
  - transmission_jse_encode
  - fuel_type_jse_encode

cat_features_engineer:
- make_fill
- model
- make_model
- type_of_vehicle
- transmission
- fuel_type

cat_features:
  - make_fill
  - make_model
  - type_of_vehicle
  - transmission
  - fuel_type
  - is_warranty
  - is_loan
  - is_coe_car
  - is_hybrid_cars
  - is_sta_evaluated_car
  - is_opc_car
  - is_low_mileage_car
  - is_premium_ad_car
  - is_rare__exotic
  - is_direct_owner_sale
  - is_vintage_cars
  - is_almost_new_car
  - is_electric_cars
  - is_parf_car
  - is_sgcarmart_warranty_cars
  - is_imported_used_vehicle
  - is_consignment_car

rf_selected_features:
  - arf_fill
  - make_model_jse_encode
  - dereg_value_fill
  - is_rare__exotic
  - mileage_fill
  - depreciation_fill
  - car_age
  - reg_date_year
  - car_age_manufactured
  - omv
  - engine_cap_fill
  - power_fill
  - coe_fill
  - road_tax_fill
  - manufactured
  - curb_weight_fill
  - no_of_owners
  - description_mean_word_len
  - make_fill_jse_encode
  - is_imported_used_vehicle
  - coe_month_left
  - accessories_mean_word_len
  - accessories_num_stopwords
  - price_count_make_fill
  - features_mean_word_len
  - coe_date_year
  - price_count_make_model
  - features_num_stopwords
  - manufactured_to_reg_year
  - type_of_vehicle_jse_encode

rf_parameters:
  max_depth: 22 
  min_samples_leaf: 2 
  min_samples_split: 2 
  n_estimators: 350
  random_state: 10

xgboost_parameters:
  max_depth: 5
  learning_rate: 0.1
  colsample_bytree: 0.7
  n_estimators: 1000
  verbose: False
  eval_metric: rmse
  reg_lambda: 8
  min_child_weight: 80
  random_state: 10

catboost_parameters:
  iterations: 400
  random_state: 10
  loss_function: RMSE
  eval_metric: RMSE
  l2_leaf_reg: 10
  random_strength: 20 
  depth: 6
  learning_rate: 0.08