target: price
num_features:
- manufactured
- no_of_owners
- omv
- features_num_words
- features_num_unique_words
- features_num_chars
- features_num_stopwords
- features_num_punctuations
- features_mean_word_len
- accessories_num_words
- accessories_num_unique_words
- accessories_num_chars
- accessories_num_stopwords
- accessories_num_punctuations
- accessories_mean_word_len
- description_num_words
- description_num_unique_words
- description_num_chars
- description_num_stopwords
- description_num_punctuations
- description_mean_word_len
- is_warranty
- is_loan
- is_coe_car
- is_hybrid_cars
- is_sta_evaluated_car
- is_opc_car
- is_low_mileage_car
- is_premium_ad_car
- is_rare__exotic
- is_direct_owner_sale
- is_vintage_cars
- is_almost_new_car
- is_electric_cars
- is_parf_car
- is_sgcarmart_warranty_cars
- is_imported_used_vehicle
- is_consignment_car
- coe_date_year
- coe_date_month
- coe_month_left
- is_lifespan_missing
- lifespan_year
- lifespan_month
- reg_date_year
- reg_date_month
- manufactured_to_reg_year
- lifespan_to_reg_year
- car_age
- car_age_manufactured
- arf_fill
- coe_fill
- coe_missing
- dereg_value_fill
- depreciation_fill
- road_tax_fill
- power_missing
- power_fill
- curb_weight_missing
- curb_weight_fill
- engine_cap_missing 
- engine_cap_fill
- mileage_missing
- mileage_fill
cat_encoding_features:
- is_auto
- is_manual
- is_missing
- is_diesel
- is_petrol-electric
- is_petrol
- is_electric
- is_mid-sized sedan
- is_sports car
- is_truck
- is_stationwagon
- is_suv
- is_mpv
- is_luxury sedan
- is_hatchback
- is_van
- is_bus/mini bus
- is_others
- price_mean_make_fill
- price_amin_make_fill
- price_amax_make_fill
- price_count_make_fill
- price_std_make_fill
- price_median_make_fill
- price_percentile_25_make_fill
- price_percentile_50_make_fill
- price_percentile_75_make_fill
- price_mean_make_model
- price_amin_make_model
- price_amax_make_model
- price_count_make_model
- price_std_make_model
- price_median_make_model
- price_percentile_25_make_model
- price_percentile_50_make_model
- price_percentile_75_make_model
- price_mean_type_of_vehicle
- price_amin_type_of_vehicle
- price_amax_type_of_vehicle
- price_count_type_of_vehicle
- price_std_type_of_vehicle
- price_median_type_of_vehicle
- price_percentile_25_type_of_vehicle
- price_percentile_50_type_of_vehicle
- price_percentile_75_type_of_vehicle
- price_mean_transmission
- price_amin_transmission
- price_amax_transmission
- price_count_transmission
- price_std_transmission
- price_median_transmission
- price_percentile_25_transmission
- price_percentile_50_transmission
- price_percentile_75_transmission
- price_mean_fuel_type
- price_amin_fuel_type
- price_amax_fuel_type
- price_count_fuel_type
- price_std_fuel_type
- price_median_fuel_type
- price_percentile_25_fuel_type
- price_percentile_50_fuel_type
- price_percentile_75_fuel_type
cat_features:
- make_fill
- model
- make_model
- type_of_vehicle
- transmission
- fuel_type